<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Version>1.0.907</Version>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>TLabs</Authors>
    <PackageDescription>Common classes for exchange project</PackageDescription>
    <RepositoryUrl>https://github.com/T-Labs/exchange-sdk</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Audit.NET" Version="32.2.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
    <PackageReference Include="TLabs.DotnetHelpers" Version="1.0.70" />
  </ItemGroup>

   <PropertyGroup>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>
</Project>
